apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hattivatti.fullname" . }}
  labels:
    {{- include "hattivatti.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "hattivatti.fullname" . }}
  replicas: {{ .Values.replicas | default 1 }}
  template:
    metadata:
      labels:
        app: {{ include "hattivatti.fullname" . }}
    spec:
      serviceAccountName: {{ include "hattivatti.serviceAccountName" . }}
      initContainers:
        - name: init-litestream
          image: litestream/litestream:0.3
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          args: ['restore', '-if-db-not-exists', '-if-replica-exists', '-o', {{ .Values.litestream.db_path }}, {{.Values.litestream.db}} ]
          resources:
              requests:
                cpu: 500m
                memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: {{ dir .Values.litestream.db_path }}
            - name: hattivatti-config-volume
              mountPath: /etc/litestream.yml
              subPath: dbs
              readOnly: true
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          resources:
              requests:
                cpu: 100m
                memory: 128Mi
          volumeMounts:
            - name: data
              mountPath: {{ dir .Values.litestream.db_path }}
          env:
          {{- range $envVarName, $secretKey := .Values.envMapping }}
          - name: {{ $envVarName }}
            valueFrom:
              secretKeyRef:
                name: {{ $.Release.Name }}-secrets
                key: {{ $envVarName }}
          {{- end }}
          - name: SQLITE_DB_PATH
            value: {{ required "db_path required" .Values.litestream.db_path }}
          - name: NAMESPACE
            value: {{ .Release.Namespace }}
          - name: MIN_OVERLAP
            value: {{ required "pgsc_calc minOverlap is missing " .Values.pgsc_calc.minOverlap | quote }}
        - name: litestream
          image: litestream/litestream:0.3
          args: ['replicate']
          resources:
              requests:
                cpu: 100m
                memory: 128Mi
          volumeMounts:
            - name: data
              mountPath: {{ dir .Values.litestream.db_path }}
            - name: hattivatti-config-volume
              mountPath: /etc/litestream.yml
              subPath: dbs
              readOnly: true
      volumes:
        - name: hattivatti-config-volume
          configMap:
            name: hattivatti-configmap
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 100Mi
