apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: helm
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["serviceaccounts", "configmaps", "pods", "secrets"]
  verbs: ["get", "create", "list", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "create", "list", "delete"]  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helm
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role 
  name: helm 
  apiGroup: rbac.authorization.k8s.io