apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
data:
{{- range $envVarName, $secretKey := .Values.envMapping }}
  {{ $envVarName }}: {{ index $.Values.secrets $secretKey | b64enc }}
{{- end }}