apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-jobconfig
data:
  input.json: {{ .Values.json_input | quote }}
  params.yml: |
{{- range $key, $value := .Values.job }}
    {{ $key }}: {{ $value }}
{{- end }}
  nxf.config: |
    workDir = {{ .Values.nxf.workBucketPath | quote }}

    process {
      executor = "google-batch"
    }

    google {
      project = {{ .Values.nxf.gcpProject | quote }}
      location = {{ .Values.nxf.location | quote }}
      batch {
        spot = {{ .Values.nxf.spot }}
      }
    }

    wave {
      enabled = {{ .Values.nxf.wave }}
    }

    fusion {
      enabled =  {{ .Values.nxf.fusion }}
    }

    tower {
      accessToken = {{ .Values.towerToken | quote }}
      workspaceId = {{ .Values.towerId | quote }}
      enabled = true
    }
  scm: |
    providers {
      ebi {
        server = 'https://gitlab.ebi.ac.uk'
        platform = 'gitlab'
      }
    }
