apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: nextflow
      containers:
        - args:
            - nextflow run https://gitlab.ebi.ac.uk/gdp-public/pgsc_calc.git -r {{ .Chart.AppVersion }} --input /opt/input.json -params-file /opt/params.yml -c /opt/nxf.config; sleep 600
          command:
            - /bin/sh
            - '-c'
          env:
            - name: NXF_SCM_FILE
              value: /opt/scm
          image: {{ .Values.baseImage }}:{{ .Values.dockerTag }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          name: nextflow
          resources:
            requests:
              cpu: 1
              memory: 2G
              ephemeral-storage: 10G
          volumeMounts:
            - name: config-volume
              mountPath: /opt/
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-jobconfig
      restartPolicy: Never
