apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-globus
stringData:
  secrets.properties: |
    globus.guest-collection.domain={{ .Values.secrets.GLOBUS_DOMAIN }}
    globus.aai.client-id={{ .Values.secrets.GLOBUS_CLIENT_ID }}
    globus.aai.client-secret={{ .Values.secrets.GLOBUS_CLIENT_SECRET }}
    globus.aai.scopes={{ .Values.secrets.GLOBUS_SCOPES }}