apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
spec:
  backoffLimit: 0
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      serviceAccountName: nextflow
      initContainers:
        - name: globflow
          image: {{ .Values.baseImage }}:{{ .Values.dockerTag }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          command: ['sh', '-c', "nextflow run https://gitlab.ebi.ac.uk/gdp-public/globflow.git -params-file /opt/params.yml -c /opt/nxf/nxf.config"]
          env:
            - name: NXF_SCM_FILE
              value: /opt/nxf/scm
          resources:
            requests:
              cpu: 1
              memory: 2G
              ephemeral-storage: 10G
          volumeMounts:
            - name: transfer-config-volume
              mountPath: /opt/
            - name: transfer-config-nxf-volume
              mountPath: /opt/nxf/
            - name: globflow-secrets
              mountPath: /opt/globflow/
              readOnly: true         
      containers:
        - name: pgsc-calc
          image: {{ .Values.baseImage }}:{{ .Values.dockerTag }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          command: ['sh', '-c', "nextflow run https://gitlab.ebi.ac.uk/gdp-public/pgsc_calc.git -r {{ .Chart.AppVersion }} -params-file /opt/params.yml -c /opt/nxf.config"]
          env:
            - name: NXF_SCM_FILE
              value: /opt/scm
          resources:
            requests:
              cpu: 1
              memory: 2G
              ephemeral-storage: 10G
          volumeMounts:
            - name: job-config-volume
              mountPath: /opt/
      volumes:
        - name: transfer-config-nxf-volume
          configMap:
            name: {{ .Release.Name }}-jobconfig
            items:
            - key: nxf.config
              path: nxf.config
            - key: scm
              path: scm
        - name: transfer-config-volume
          configMap:
            name: {{ .Release.Name }}-transferconfig              
        - name: globflow-secrets
          secret:
            secretName: {{ .Release.Name }}-globus
        - name: job-config-volume
          configMap:
            name: {{ .Release.Name }}-jobconfig
      restartPolicy: Never
