apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
spec:
  ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished | default 172800 }}
  backoffLimit: {{ .Values.backoffLimit | default 0 }}
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      serviceAccountName: {{.Values.serviceAccount.name }}
      initContainers:
        - name: globflow
          image: {{ .Values.baseImage }}:{{ .Values.dockerTag }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          command:
            - "nextflow"
            - "run"
            - "gdp-public/globflow"
            - "-hub"
            - "ebi"
            - "-r"
            - "2.0.0"
            - "-params-file"
            - "/opt/nxf/params.yml"
            - "-c"
            - "/opt/nxf/nxf.config"
            - "--decrypt"
          env:
            - name: NXF_SCM_FILE
              value: /opt/nxf/scm
          resources:
            requests:
              cpu: "1"
              memory: 2G
              ephemeral-storage: 10G
          volumeMounts:
            - name: transfer-config
              mountPath: /opt/nxf/
              readOnly: true
            - name: globflow-secrets
              mountPath: /opt/globflow/
              readOnly: true
      containers:
        - name: pgsc-calc
          image: {{ .Values.baseImage }}:{{ .Values.dockerTag }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          command:
            - "nextflow"
            - "run"
            - "-name"
            - "{{ .Release.Namespace }}-{{ .Release.Name }}"
            - "gdp-public/pgsc_calc"
            - "-hub"
            - "ebi"
            - "-r"
            - "{{ .Chart.AppVersion }}"
            - "-params-file"
            - "/opt/nxf/params.yml"
            - "-c"
            - "/opt/nxf/nxf.config"
          env:
            - name: NXF_SCM_FILE
              value: /opt/nxf/scm
          resources:
            requests:
              cpu: "1"
              memory: 2G
              ephemeral-storage: 10G
          volumeMounts:
            - name: pgs-config-volume
              mountPath: /opt/nxf
              readOnly: true
      volumes:
        - name: transfer-config
          configMap:
            name: {{ .Release.Name }}-transfer-config
            items:
            - key: nxf.config
              path: nxf.config
            - key: scm
              path: scm
            - key: params.yml
              path: params.yml
            - key: input.json
              path: input.json
            - key: key.json
              path: key.json
        - name: globflow-secrets
          secret:
            secretName: {{ .Release.Name }}-transfer-secrets
        - name: pgs-config-volume
          configMap:
            name: {{ .Release.Name }}-pgs-config
            items:
            - key: nxf.config
              path: nxf.config
            - key: input.json
              path: input.json
            - key: params.yml
              path: params.yml
            - key: scm
              path: scm
      restartPolicy: {{ .Values.restartPolicy | default "Never" }}
