apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-globus
stringData:
  secrets.properties: |
    globus.guest-collection.domain={{ .Values.secrets.globusDomain }}
    globus.aai.client-id={{ .Values.secrets.globusClientId }}
    globus.aai.client-secret={{ .Values.secrets.globusClientSecret }}
    globus.aai.scopes={{ .Values.secrets.globusScopes }}