{{- $serviceAccountExists := lookup "v1" "ServiceAccount" .Release.Namespace .Values.serviceAccount.name -}}
{{- if not $serviceAccountExists -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
{{- end }}