apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-transfer-secrets
stringData:
  application.properties: |
    #####################################################################################
    # Application config
    #####################################################################################
    spring.main.web-application-type=none
    data.copy.buffer-size=8192
    #####################################################################################
    # Apache HttpClient connection config
    #####################################################################################
    webclient.connection.pipe-size=${data.copy.buffer-size}
    webclient.connection.connection-timeout=5
    webclient.connection.socket-timeout=0
    webclient.connection.read-write-timeout=30000
    #####################################################################################
    # File download retry config
    #####################################################################################
    # EXPONENTIAL/FIXED
    file.download.retry.strategy=FIXED
    file.download.retry.attempts.max=3
    # Exponential
    file.download.retry.attempts.delay=1000
    file.download.retry.attempts.maxDelay=30000
    file.download.retry.attempts.multiplier=2
    # Fixed
    file.download.retry.attempts.back-off-period=2000
    #####################################################################################
    # Globus config
    #####################################################################################
    globus.guest-collection.domain={{ required ".Values.secrets.globusDomain is required" .Values.secrets.globusDomain }}
    #Oauth
    globus.aai.access-token.uri=https://auth.globus.org/v2/oauth2/token
    globus.aai.client-id={{ required ".Values.secrets.globusClientId is required" .Values.secrets.globusClientId }}
    globus.aai.client-secret={{ required ".Values.secrets.globusClientSecret is required" .Values.secrets.globusClientSecret }}
    globus.aai.scopes=https://auth.globus.org/scopes/c1e6310c-11d5-4e8a-9443-211884f04c6f/https
    #####################################################################################
    # Logging config
    #####################################################################################
    logging.level.uk.ac.ebi.intervene=INFO
    logging.level.org.springframework=WARN
    logging.level.org.apache.http=WARN
    logging.level.org.apache.http.wire=WARN
  application-crypt4gh-secret-manager.properties: |
    #####################################################################################
    # Crypt4gh config
    #####################################################################################
    crypt4gh.binary-path=/opt/bin/crypt4gh
    crypt4gh.shell-path=/bin/bash -c
    #####################################################################################
    # Intervene service config
    #####################################################################################
    intervene.key-handler.basic-auth=Basic {{ required ".Values.secrets.keyHandlerToken is required" .Values.secrets.keyHandlerToken }}
    intervene.key-handler.secret-key.password={{ required ".Values.secrets.keyHandlerPassword is required" .Values.secrets.keyHandlerPassword }}
    intervene.key-handler.base-url={{ required ".Values.secrets.keyHandlerURL is required" .Values.secrets.keyHandlerURL }}
    intervene.key-handler.keys.uri=/key/{secretId}/version/{secretIdVersion}
