name: Ruff linting
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1

  pyright:
    runs-on: ubuntu-latest
    steps:
    - uses: jakebailey/pyright-action@v2
      with:
        version: 1.1.355